pipelines:
  default:
    - step:
        name: Deploy to test
        deployment: test
        # trigger: manual  # Uncomment to make this a manual deployment.
        script:
          - echo "Deploying"
          - cat ./post-push.sh | ssh ubuntu@13.127.245.252
          - echo "deployed"
