# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: atlassian/default-image:2

pipelines:
  default:
    - step:
        name: Deploy to test
        deployment: test
        # trigger: manual  # Uncomment to make this a manual deployment.
        script:
          - echo "Deploying"
           script:
            - cat ./post-push.sh | ssh ubuntu@65.2.149.29
            - echo "deployed"
